### ISSUE TITLE
Return value of Roave\DoctrineSimpleCache\SimpleCacheAdapter::has() must be of the type boolean, integer returned

### ISSUE THREAD

**Issue by Sirgalas** [Roave/DoctrineSimpleCache#29] opened 2018-08-20 11:00 UTC
here so I connect

```php
$redis=new \Redis();
        $redis->connect('localhost',6379);
         $cash=new \Doctrine\Common\Cache\RedisCache();
         $cash->setRedis($redis);
         return new SimpleCacheAdapter($cash);
```
this is the answer

> TypeError
> Return value of Roave\DoctrineSimpleCache\SimpleCacheAdapter::has() must be of the type boolean, integer returned

know exactly what

 ```php
public function has($key) : bool
    {
        $this->validateKey($key);
        return $this->doctrineCache->contains($key);
    }
```
return int 0

what's wrong

**Comment by Ocramius** [comment] 2018-08-20 11:27
@Sirgalas can you clarify on the resolution? Is it a bug in Redis, Doctrine or this library?

**Comment by Sirgalas** [comment] 2018-08-20 12:39
всетаки в библиотеке. Оказывается это я в vendor  вот сюда Roave\DoctrineSimpleCache в метод has внес изменения закоментировал  тип возврашаемого значения.
Вот так
```
public function has($key) // : bool
    {
        $this->validateKey($key);
        return $this->doctrineCache->contains($key);
    }
```

**Comment by Sirgalas** [comment] 2018-08-20 12:39
so there is no mistake :)

**Comment by Ocramius** [comment] 2018-08-20 12:40
Alright, closing then.

**Comment by asgrim** [comment] 2018-08-20 12:41
Translate for reference:
> all the same in the library. It turns out that I'm in the vendor that's where Roave\DoctrineSimpleCache in the has method introduced the changes commented on the type of the return value.

**Closed by Ocramius** 2018-08-20 12:40 UTC
Labels: bug

**Comment by Sirgalas** [comment] 2018-08-20 12:47
Sorry for my English, google translate :)

**Comment by Sirgalas** [comment] 2018-08-20 12:49
Why did you close the problems in your library

**Comment by Ocramius** [comment] 2018-08-20 13:02
@Sirgalas in https://github.com/Roave/DoctrineSimpleCache/issues/29#issuecomment-414302547 you mentioned "there is no mistake".

According to https://github.com/doctrine/cache/blob/5e65fc393ecc17e395ac44d7b855dcf5e6864f34/lib/Doctrine/Common/Cache/Cache.php#L38-L40, the return type of `contains()` is `bool`, so the problem (if there is any) needs to be fixed there.

**Comment by asgrim** [comment] 2018-08-20 14:30
Not sure how an int is returned, reaidng through `RedisCache`:

https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php#L100-L106

Only a `bool` should ever be returned...

**Comment by Sirgalas** [comment] 2018-08-21 16:08
And the same does not return int (0 or 1).What does it seem to me equivalent to true and false

**Comment by asgrim** [comment] 2018-08-21 16:10
So my point is, if you're using `RedisCache` from Doctrine\Cache (Which returns `bool` always, then I'm not sure how you're getting

> TypeError
> Return value of Roave\DoctrineSimpleCache\SimpleCacheAdapter::has() must be of the type boolean, integer returned

Could you clarify please? Steps to reproduce? Unless more information can be provided, I'm really not sure what you're looking for here...

**Comment by Ocramius** [comment] 2018-08-21 16:30
Also make sure you are running all latest versions of all the involved
libraries.
Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Sirgalas** [comment] 2018-08-21 16:53
@asgrim I wrote the code at the top where an error occurred.

**Comment by Ocramius** [comment] 2018-08-21 16:55
Yes. If `RedisCache` returns `1` or `0` instead of `true` or `false`, then that's a bug in doctrine/cache

**Comment by Sirgalas** [comment] 2018-08-21 16:57
@Ocramius here is data about packages from composer
"symfony / cache": "^4.1",
""rove / doctrine-simplecache": "^2.1"
php version 7.2

**Comment by Ocramius** [comment] 2018-08-21 16:58
Check the version of `doctrine/cache` in your `composer.lock`

**Comment by Sirgalas** [comment] 2018-08-21 17:00
@Ocramius  You saw what I wrote to them. And then they there is a cast to the `return type (bool)...` 
And yet I do not consider it superfluous if you will also lead to a boolean. There will be no error.

**Comment by Ocramius** [comment] 2018-08-21 17:04
@Sirgalas if the declared type coming from the `doctrine/cache`` library is incorrect, that's not a bug here, but in that library.

@asgrim just went through it, and says that it may be a redis extension bug.

**Comment by Sirgalas** [comment] 2018-08-21 17:05
@Ocramius 
 composer show symfony/cache
Do not run Composer as root/super user! See https://getcomposer.org/root for details
name     : symfony/cache
descrip. : Symfony Cache component with PSR-6, PSR-16, and tags
keywords : caching, psr6
versions : * v4.1.3
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/symfony/cache.git c666a5bbfeb1fe05c7b91d46810f405c8bea14cf
dist     : [zip] https://api.github.com/repos/symfony/cache/zipball/c666a5bbfeb1fe05c7b91d46810f405c8bea14cf c666a5bbfeb1fe05c7b91d46810f405c8bea14cf
names    : symfony/cache, psr/cache-implementation, psr/simple-cache-implementation

autoload
psr-4
Symfony\Component\Cache\ => .
exclude-from-classmap

requires
php ^7.1.3
psr/cache ~1.0
psr/log ~1.0
psr/simple-cache ^1.0

requires (dev)
cache/integration-tests dev-master
doctrine/cache ~1.6
doctrine/dbal ~2.4
predis/predis ~1.0

provides
psr/cache-implementation 1.0
psr/simple-cache-implementation 1.0

conflicts
symfony/var-dumper <3.4

**Comment by Sirgalas** [comment] 2018-08-21 17:05
is that better ?

**Comment by Ocramius** [comment] 2018-08-21 17:05
We use `doctrine/cache`, not `symfony/cache` :-)

**Comment by asgrim** [comment] 2018-08-21 17:08
@Sirgalas I've confirmed it's a bug upstream in doctrine/cache#275 - thanks for the useful information :+1:

**Comment by Ocramius** [comment] 2018-08-21 17:11
Closing here then, let's move over there :+1:

**Comment by Sirgalas** [comment] 2018-08-21 17:14
@Ocramius  oh, sorry
Do not run Composer as root/super user! See https://getcomposer.org/root for details
name     : doctrine/cache
descrip. : Caching library offering an object-oriented API for many cache backends
keywords : cache, caching
versions : * v1.7.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/doctrine/cache.git b3217d58609e9c8e661cd41357a54d926c4a2a1a
dist     : [zip] https://api.github.com/repos/doctrine/cache/zipball/b3217d58609e9c8e661cd41357a54d926c4a2a1a b3217d58609e9c8e661cd41357a54d926c4a2a1a
names    : doctrine/cache

autoload
psr-4
Doctrine\Common\Cache\ => lib/Doctrine/Common/Cache

requires
php ~7.1

requires (dev)
alcaeus/mongo-php-adapter ^1.1
mongodb/mongodb ^1.1
phpunit/phpunit ^5.7
predis/predis ~1.0

suggests
alcaeus/mongo-php-adapter Required to use legacy MongoDB driver

conflicts
doctrine/common >2.2,<2.4

**Comment by Sirgalas** [comment] 2018-08-21 17:27
@asgrim  
If you want Your library worked until doctrine/cashe fixes this bug I would recommend to you, and since you have class `SimpleCacheAdapter` final urge to keep in line 204 the following changes.
` return (bool)$this->doctrineCache->contains($key);`
errors it will not but rid of these errors continue

**Comment by Ocramius** [comment] 2018-08-21 17:30
No, this is an upstream bug, and fixing the problem here should *NOT* be done.

**Comment by Sirgalas** [comment] 2018-08-21 17:38
@Ocramius I will say as for me. If my final product doesn't work. Even due to some library to which I have nothing better I will try to correct and with a clear conscience I'll wait for the hotfix. I'll let it suffer for its end users. Just if tomorrow will not be fixed then I will have to make a fork and work itself.

**Comment by Ocramius** [comment] 2018-08-21 17:44
@Sirgalas making a fork because you have time pressure is one thing, but problems should be fixed at their source.

If we ran static analysis on this codebase, it would fail (if we introduce a cast) because of the redundant cast.

Problems should be fixed at their source, not in intermediate layers: that just leads to more problems.

**Comment by asgrim** [comment] 2018-08-21 17:59
Locking this as upstream fix is on the way, nothing constructive to be added here.
